/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hhz.graphicaluserinterface;

import com.google.gson.Gson;
import static hhz.graphicaluserinterface.GraphicHelperClass.ExtractLineBoundingBox;
import static hhz.graphicaluserinterface.GraphicHelperClass.ExtractLineText;
import static hhz.graphicaluserinterface.GraphicHelperClass.scaleFactor;
import hhz.ocr.DrawBoundingBox;
import hhz.ocr.GraphicHelper;
import hhz.ocr.json.BoundingBoxObject;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import org.apache.commons.io.comparator.LastModifiedFileComparator;
import org.json.simple.JSONObject;

/**
 *
 * @author Valerij
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        mainPanel = new javax.swing.JPanel();
        galleryViewPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        g1Panel = new javax.swing.JPanel();
        g1Label = new javax.swing.JLabel();
        g2Panel = new javax.swing.JPanel();
        g2Label = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        g3Panel = new javax.swing.JPanel();
        g3Label = new javax.swing.JLabel();
        g4Panel = new javax.swing.JPanel();
        g4Label = new javax.swing.JLabel();
        g5Panel = new javax.swing.JPanel();
        g5Label = new javax.swing.JLabel();
        lastImage = new javax.swing.JLabel();
        nextImage = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        openDirectoryButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        currentDirectoryPathField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        StartLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        virtualRunaroundPanel = new javax.swing.JPanel();
        reportingPanel = new javax.swing.JPanel();
        settingsPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        sidepanel3 = new javax.swing.JPanel();
        gallaryview3 = new javax.swing.JPanel();
        jLabelGalleryImage3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        virtualrunaround = new javax.swing.JPanel();
        jLabelVirtualImage = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        reporting = new javax.swing.JPanel();
        jLabelReportingLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        settings = new javax.swing.JPanel();
        jLabelSettingsImage = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        logopanel = new javax.swing.JPanel();
        jLabelLogoImage = new javax.swing.JLabel();
        footerpanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());

        galleryViewPanel.setBackground(new java.awt.Color(255, 255, 153));
        galleryViewPanel.setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 35, 42));
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 860, 600));

        g1Panel.setBackground(new java.awt.Color(204, 35, 42));

        g1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        g1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/no-stopping128.png"))); // NOI18N
        g1Label.setToolTipText(" Temporarily unavailable");
        g1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                g1LabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout g1PanelLayout = new javax.swing.GroupLayout(g1Panel);
        g1Panel.setLayout(g1PanelLayout);
        g1PanelLayout.setHorizontalGroup(
            g1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(g1Label, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
        );
        g1PanelLayout.setVerticalGroup(
            g1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(g1Label, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
        );

        jPanel3.add(g1Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 680, -1, 131));

        g2Panel.setBackground(new java.awt.Color(204, 35, 42));
        g2Panel.setToolTipText("");

        g2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        g2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/no-stopping128.png"))); // NOI18N
        g2Label.setToolTipText(" Temporarily unavailable");
        g2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                g2LabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout g2PanelLayout = new javax.swing.GroupLayout(g2Panel);
        g2Panel.setLayout(g2PanelLayout);
        g2PanelLayout.setHorizontalGroup(
            g2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(g2Label, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
        );
        g2PanelLayout.setVerticalGroup(
            g2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(g2Label, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
        );

        jPanel3.add(g2Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 680, -1, 131));

        jTextPane1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(204, 35, 42));
        jScrollPane2.setViewportView(jTextPane1);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 90, 270, 470));

        g3Panel.setBackground(new java.awt.Color(204, 35, 42));

        g3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        g3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/no-stopping128.png"))); // NOI18N
        g3Label.setToolTipText(" Temporarily unavailable");
        g3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                g3LabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout g3PanelLayout = new javax.swing.GroupLayout(g3Panel);
        g3Panel.setLayout(g3PanelLayout);
        g3PanelLayout.setHorizontalGroup(
            g3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(g3Label, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
        );
        g3PanelLayout.setVerticalGroup(
            g3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(g3Label, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
        );

        jPanel3.add(g3Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 680, -1, 131));

        g4Panel.setBackground(new java.awt.Color(204, 35, 42));

        g4Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        g4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/no-stopping128.png"))); // NOI18N
        g4Label.setToolTipText(" Temporarily unavailable");
        g4Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                g4LabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout g4PanelLayout = new javax.swing.GroupLayout(g4Panel);
        g4Panel.setLayout(g4PanelLayout);
        g4PanelLayout.setHorizontalGroup(
            g4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(g4Label, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
        );
        g4PanelLayout.setVerticalGroup(
            g4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(g4Label, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
        );

        jPanel3.add(g4Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 680, -1, -1));

        g5Panel.setBackground(new java.awt.Color(204, 35, 42));

        g5Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        g5Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/no-stopping128.png"))); // NOI18N
        g5Label.setToolTipText(" Temporarily unavailable");
        g5Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                g5LabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout g5PanelLayout = new javax.swing.GroupLayout(g5Panel);
        g5Panel.setLayout(g5PanelLayout);
        g5PanelLayout.setHorizontalGroup(
            g5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(g5Label, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
        );
        g5PanelLayout.setVerticalGroup(
            g5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(g5Label, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
        );

        jPanel3.add(g5Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 680, -1, -1));

        lastImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lastImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backRedd.png"))); // NOI18N
        lastImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lastImageMouseClicked(evt);
            }
        });
        jPanel3.add(lastImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 60, 80));

        nextImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nextImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nextRed.png"))); // NOI18N
        nextImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextImageMouseClicked(evt);
            }
        });
        jPanel3.add(nextImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 320, 50, 80));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 35, 42));
        jLabel12.setText("Refresh");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 600, 40, 30));

        jSeparator1.setForeground(new java.awt.Color(204, 35, 42));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 640, 290, 10));

        openDirectoryButton.setForeground(new java.awt.Color(204, 35, 42));
        openDirectoryButton.setText("Open directory");
        openDirectoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openDirectoryButtonActionPerformed(evt);
            }
        });
        jPanel3.add(openDirectoryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 660, 120, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 35, 42));
        jLabel13.setText(" Current directory:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 730, 110, 20));

        currentDirectoryPathField.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        currentDirectoryPathField.setForeground(new java.awt.Color(204, 35, 42));
        currentDirectoryPathField.setSelectedTextColor(new java.awt.Color(204, 35, 42));
        jPanel3.add(currentDirectoryPathField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 760, 260, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 35, 42));
        jLabel15.setText("CAM 5");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 820, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 35, 42));
        jLabel16.setText("CAM 1");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 820, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 35, 42));
        jLabel17.setText("CAM 2");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 820, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 35, 42));
        jLabel18.setText("CAM 3");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 820, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 35, 42));
        jLabel19.setText("CAM 4");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 820, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh1.png"))); // NOI18N
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 600, 40, 30));

        StartLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/play-button1.png"))); // NOI18N
        StartLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StartLabelMouseClicked(evt);
            }
        });
        jPanel3.add(StartLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 600, 30, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 35, 42));
        jLabel1.setText("Infobox");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 60, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 35, 42));
        jLabel20.setText(" Change picture directory:");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 660, 140, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 35, 42));
        jLabel21.setText("Start");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 600, 40, 30));

        galleryViewPanel.add(jPanel3);

        mainPanel.add(galleryViewPanel, "card5");

        virtualRunaroundPanel.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout virtualRunaroundPanelLayout = new javax.swing.GroupLayout(virtualRunaroundPanel);
        virtualRunaroundPanel.setLayout(virtualRunaroundPanelLayout);
        virtualRunaroundPanelLayout.setHorizontalGroup(
            virtualRunaroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
        );
        virtualRunaroundPanelLayout.setVerticalGroup(
            virtualRunaroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 851, Short.MAX_VALUE)
        );

        mainPanel.add(virtualRunaroundPanel, "card4");

        reportingPanel.setBackground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout reportingPanelLayout = new javax.swing.GroupLayout(reportingPanel);
        reportingPanel.setLayout(reportingPanelLayout);
        reportingPanelLayout.setHorizontalGroup(
            reportingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
        );
        reportingPanelLayout.setVerticalGroup(
            reportingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 851, Short.MAX_VALUE)
        );

        mainPanel.add(reportingPanel, "card3");

        settingsPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 35, 42));
        jLabel2.setText("OCR recognition settings");

        jSeparator3.setForeground(new java.awt.Color(204, 35, 42));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 35, 42));
        jLabel3.setText("Object recognition settings ");

        jSeparator4.setForeground(new java.awt.Color(204, 35, 42));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 35, 42));
        jLabel10.setText(" General");

        jSeparator5.setForeground(new java.awt.Color(204, 35, 42));

        javax.swing.GroupLayout settingsPanelLayout = new javax.swing.GroupLayout(settingsPanel);
        settingsPanel.setLayout(settingsPanelLayout);
        settingsPanelLayout.setHorizontalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        settingsPanelLayout.setVerticalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(settingsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(settingsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(settingsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(802, Short.MAX_VALUE))
        );

        mainPanel.add(settingsPanel, "card2");

        jPanel1.setLayout(new java.awt.BorderLayout());

        sidepanel3.setBackground(new java.awt.Color(204, 35, 42));
        sidepanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gallaryview3.setBackground(new java.awt.Color(160, 35, 42));
        gallaryview3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gallaryviewMouseClicked(evt);
            }
        });

        jLabelGalleryImage3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGalleryImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gallery.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gallery View");

        javax.swing.GroupLayout gallaryview3Layout = new javax.swing.GroupLayout(gallaryview3);
        gallaryview3.setLayout(gallaryview3Layout);
        gallaryview3Layout.setHorizontalGroup(
            gallaryview3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gallaryview3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelGalleryImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        gallaryview3Layout.setVerticalGroup(
            gallaryview3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gallaryview3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(gallaryview3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(jLabelGalleryImage3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidepanel3.add(gallaryview3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 280, -1));

        virtualrunaround.setBackground(new java.awt.Color(204, 35, 42));
        virtualrunaround.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                virtualrunaroundMouseClicked(evt);
            }
        });

        jLabelVirtualImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVirtualImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Virtual Runaround");

        javax.swing.GroupLayout virtualrunaroundLayout = new javax.swing.GroupLayout(virtualrunaround);
        virtualrunaround.setLayout(virtualrunaroundLayout);
        virtualrunaroundLayout.setHorizontalGroup(
            virtualrunaroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(virtualrunaroundLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelVirtualImage, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        virtualrunaroundLayout.setVerticalGroup(
            virtualrunaroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(virtualrunaroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(virtualrunaroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(jLabelVirtualImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidepanel3.add(virtualrunaround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 280, -1));

        reporting.setBackground(new java.awt.Color(204, 35, 42));
        reporting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportingMouseClicked(evt);
            }
        });

        jLabelReportingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReportingLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/analysis.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Reporting");

        javax.swing.GroupLayout reportingLayout = new javax.swing.GroupLayout(reporting);
        reporting.setLayout(reportingLayout);
        reportingLayout.setHorizontalGroup(
            reportingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportingLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelReportingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        reportingLayout.setVerticalGroup(
            reportingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(reportingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(jLabelReportingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidepanel3.add(reporting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 280, -1));

        settings.setBackground(new java.awt.Color(204, 35, 42));
        settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsMouseClicked(evt);
            }
        });

        jLabelSettingsImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSettingsImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/settings.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Settings");

        javax.swing.GroupLayout settingsLayout = new javax.swing.GroupLayout(settings);
        settings.setLayout(settingsLayout);
        settingsLayout.setHorizontalGroup(
            settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelSettingsImage, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        settingsLayout.setVerticalGroup(
            settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel11)
                    .addComponent(jLabelSettingsImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidepanel3.add(settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 280, -1));

        logopanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabelLogoImage.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLogoImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogoImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kauflandLogo.png"))); // NOI18N

        javax.swing.GroupLayout logopanelLayout = new javax.swing.GroupLayout(logopanel);
        logopanel.setLayout(logopanelLayout);
        logopanelLayout.setHorizontalGroup(
            logopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logopanelLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabelLogoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        logopanelLayout.setVerticalGroup(
            logopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logopanelLayout.createSequentialGroup()
                .addComponent(jLabelLogoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sidepanel3.add(logopanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 280, 30));

        footerpanel.setBackground(new java.awt.Color(255, 255, 255));
        footerpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 35, 42));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("© Copyright by HHZ");
        footerpanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 0, 115, 36));

        sidepanel3.add(footerpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 820, 280, 30));

        jPanel1.add(sidepanel3, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void settingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseClicked
        //removing panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        //set menu color
        settings.setBackground(new Color(160, 35, 42));
        reporting.setBackground(new Color(204, 35, 42));
        virtualrunaround.setBackground(new Color(204, 35, 42));
        gallaryview3.setBackground(new Color(204, 35, 42));
        //adding virtualrunaroundPanel
        mainPanel.add(settingsPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_settingsMouseClicked

    private void reportingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportingMouseClicked
        //removing panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        //set menu color
        settings.setBackground(new Color(204, 35, 42));
        reporting.setBackground(new Color(160, 35, 42));
        virtualrunaround.setBackground(new Color(204, 35, 42));
        gallaryview3.setBackground(new Color(204, 35, 42));
        //adding virtualrunaroundPanel
        mainPanel.add(reportingPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_reportingMouseClicked

    private void virtualrunaroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_virtualrunaroundMouseClicked
        //removing panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        //set menu color
        settings.setBackground(new Color(204, 35, 42));
        reporting.setBackground(new Color(204, 35, 42));
        virtualrunaround.setBackground(new Color(160, 35, 42));
        gallaryview3.setBackground(new Color(204, 35, 42));
        //adding virtualrunaroundPanel
        mainPanel.add(virtualRunaroundPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_virtualrunaroundMouseClicked

    private void gallaryviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gallaryviewMouseClicked
        //removing panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        //set menu color
        settings.setBackground(new Color(204, 35, 42));
        reporting.setBackground(new Color(204, 35, 42));
        virtualrunaround.setBackground(new Color(204, 35, 42));
        gallaryview3.setBackground(new Color(160, 35, 42));
        //adding virtualrunaroundPanel
        mainPanel.add(galleryViewPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_gallaryviewMouseClicked

    private void openDirectoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openDirectoryButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            currentDirectoryPathField.setText(chooser.getSelectedFile().getAbsolutePath());
            System.out.println("You chose to open this directory: "
                    + chooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_openDirectoryButtonActionPerformed

    //Globale shared Variablen
    static float newScaleFactorHeight;
    static float newScaleFactorWidth;
    static List<String> imagePath;
    static List<String> imagesJsonPath;
    int[] allXCoordinatesOfBoundingBox;
    int[] allYCoordinatesOfBoundingBox;
    static List<String> imagePahtCopyForCamEvent;
    static List<String> imagesJsonPahtCopyForCamEvent;
    private void StartLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartLabelMouseClicked
        Map<String, byte[]> imagePathMap = new HashMap<>();

        String directoryPath = currentDirectoryPathField.getText();
        if (!directoryPath.equals("")) {

            try {
                FileHelperClass fhc = new FileHelperClass();
                imagePath = fhc.sortPathsByTheFolderAndCreationTime(directoryPath);
                if (!imagePath.isEmpty() || imagePath != null) {
                    imagesJsonPath = fhc.ChangeFileExtensionToDotJson(imagePath);
                    //initialisiere g1Label bis g5Label
                    boolean emptyCondition = setFirstPictureToCamLabelN(imagePath);

                    imagePahtCopyForCamEvent = imagePath;
                    imagesJsonPahtCopyForCamEvent = imagesJsonPath;
                    //Skalierungswerte für Start der Application festlegen
                    if (!emptyCondition) {
                        getScaledImageIconFromImagePath(imagePath.get(0));
                        jLabel9.setText("Please choose an available cam view from below");
                        jLabel9.setHorizontalAlignment(JLabel.CENTER);
                    } else {
                        JOptionPane.showMessageDialog(mainPanel, "Please choose a directory with cam1 to cam5 folders!");
                    }
                }

            } catch (IOException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(mainPanel, "Please first choose the directory with analysed images!");
            }
        } else {
            JOptionPane.showMessageDialog(mainPanel, "Please first choose the directory with analysed images!");
        }
    }//GEN-LAST:event_StartLabelMouseClicked

    public boolean setFirstPictureToCamLabelN(List<String> imagePaths) {
        boolean cam1IsSet = false;
        boolean cam2IsSet = false;
        boolean cam3IsSet = false;
        boolean cam4IsSet = false;
        boolean cam5IsSet = false;
        boolean emptyCondition = false;
        for (String p : imagePaths) {
            switch (FileHelperClass.getDirectoryName(p)) {
                case "cam1":
                    if (!cam1IsSet) {
                        g1Label.setIcon(getScaledImageIconFromImagePathForCamLabel(p));
                        g1Label.setToolTipText("Cam1");
                        cam1IsSet = true;
                    }
                    break;
                case "cam2":
                    if (!cam2IsSet) {
                        g2Label.setIcon(getScaledImageIconFromImagePathForCamLabel(p));
                        g2Label.setToolTipText("Cam2");
                        cam2IsSet = true;
                    }
                    break;
                case "cam3":
                    if (!cam3IsSet) {
                        g3Label.setIcon(getScaledImageIconFromImagePathForCamLabel(p));
                        g3Label.setToolTipText("Cam3");
                        cam3IsSet = true;
                    }
                    break;
                case "cam4":
                    if (!cam4IsSet) {
                        g4Label.setIcon(getScaledImageIconFromImagePathForCamLabel(p));
                        g4Label.setToolTipText("Cam4");
                        cam4IsSet = true;
                    }
                    break;
                case "cam5":
                    if (!cam5IsSet) {
                        g5Label.setIcon(getScaledImageIconFromImagePathForCamLabel(p));
                        g5Label.setToolTipText("Cam5");
                        cam5IsSet = true;
                    }
                    break;
                default:
                    break;

            }
        }
        if (!cam1IsSet) {
            g1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/no-stopping128.png")));
            g1Label.setToolTipText("Temporarily unavailable");
        }
        if (!cam2IsSet) {
            g2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/no-stopping128.png")));
            g2Label.setToolTipText("Temporarily unavailable");
        }
        if (!cam3IsSet) {
            g3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/no-stopping128.png")));
            g3Label.setToolTipText("Temporarily unavailable");
        }
        if (!cam4IsSet) {
            g4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/no-stopping128.png")));
            g3Label.setToolTipText("Temporarily unavailable");
        }
        if (!cam5IsSet) {
            g5Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/no-stopping128.png")));
            g5Label.setToolTipText("Temporarily unavailable");
        }
        if (!cam1IsSet && !cam2IsSet && !cam1IsSet && !cam1IsSet && !cam1IsSet) {
            jLabel9.setBackground(Color.WHITE);
            emptyCondition = true;
        }

        return emptyCondition;
    }

    private ImageIcon getScaledImageIconFromImagePath(String imagePath) {
        BufferedImage img = null;
        Image image = null;
        try {
            img = ImageIO.read(new File(imagePath));
        } catch (IOException e) {
            e.printStackTrace();
            System.exit(1);
        }
        newScaleFactorWidth = img.getWidth() / jLabel9.getWidth();
        newScaleFactorHeight = img.getHeight() / jLabel9.getHeight();
        if (newScaleFactorWidth != 0 || newScaleFactorHeight != 0) {
            image = img.getScaledInstance((int) (img.getWidth() / newScaleFactorWidth), (int) (img.getHeight() / newScaleFactorHeight), Image.SCALE_SMOOTH);
        } else {
            image = img;
        }

        return new ImageIcon(image);
    }

    private ImageIcon getScaledImageIconFromImagePathForCamLabel(String imagePath) {
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(imagePath));
        } catch (IOException e) {
            e.printStackTrace();
            System.exit(1);
        }
        float newScaleFactorWidth = img.getWidth() / g1Label.getWidth();
        float newScaleFactorHeight = img.getHeight() / g1Label.getHeight();
        Image image = img.getScaledInstance((int) (img.getWidth() / newScaleFactorWidth), (int) (img.getHeight() / newScaleFactorHeight), Image.SCALE_SMOOTH);
        return new ImageIcon(image);
    }

    private String getRecognizedText(BoundingBoxObject bbo) {
        return "Folgender Text wurde erkannt: " + "\n\n" + ExtractLineText(bbo);
    }

    private void setXAndYCoordinates(BoundingBoxObject bbo) {
        List<Integer> lineBoundingBox = ExtractLineBoundingBox(bbo);
        allXCoordinatesOfBoundingBox = GraphicHelperClass.ListToIntArray(GraphicHelperClass.ExtractTheXCoordinates(lineBoundingBox));
        allYCoordinatesOfBoundingBox = GraphicHelperClass.ListToIntArray(GraphicHelperClass.ExtractTheYCoordinates(lineBoundingBox));
    }

    int sliderIndex = 1;
    private void lastImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lastImageMouseClicked
        if (sliderIndex == imagePahtCopyForCamEvent.size()) {
            sliderIndex = imagePahtCopyForCamEvent.size() - 2;
        }
        if (sliderIndex >= 0 && sliderIndex < imagePahtCopyForCamEvent.size()) {
           
          //  if (sliderIndex >= 0) {
                BoundingBoxObject bbo = GraphicHelperClass.getInitializedBoundingBoxObject(imagesJsonPahtCopyForCamEvent.get(sliderIndex));
                setXAndYCoordinates(bbo);
                String recognizedText = getRecognizedText(bbo);
                ImageIcon imageIcon = getScaledImageIconFromImagePath(imagePahtCopyForCamEvent.get(sliderIndex));

                jTextPane1.setText(recognizedText);
                jLabel9.setIcon(imageIcon);
                repaint(jLabel9.getGraphics());
                sliderIndex--;
          //  }
        }
    }//GEN-LAST:event_lastImageMouseClicked

    private void nextImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextImageMouseClicked
        if (sliderIndex < 0) {
            sliderIndex = 1;
        }
        if (sliderIndex >= 0 && sliderIndex < imagePahtCopyForCamEvent.size()) {
            
          //  if (sliderIndex < imagePahtCopyForCamEvent.size()) {
                BoundingBoxObject bbo = GraphicHelperClass.getInitializedBoundingBoxObject(imagesJsonPahtCopyForCamEvent.get(sliderIndex));
                setXAndYCoordinates(bbo);
                String recognizedText = getRecognizedText(bbo);
                ImageIcon imageIcon = getScaledImageIconFromImagePath(imagePahtCopyForCamEvent.get(sliderIndex));

                jTextPane1.setText(recognizedText);
                jLabel9.setIcon(imageIcon);
                repaint(jLabel9.getGraphics());
                sliderIndex++;
           // }
        }
    }//GEN-LAST:event_nextImageMouseClicked
    private void g1LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g1LabelMouseClicked
        setGLabelSelectionToTextAreaAndMainPanel("cam1");
    }//GEN-LAST:event_g1LabelMouseClicked
    private void g2LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g2LabelMouseClicked
        setGLabelSelectionToTextAreaAndMainPanel("cam2");
    }//GEN-LAST:event_g2LabelMouseClicked
    private void g3LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g3LabelMouseClicked
        setGLabelSelectionToTextAreaAndMainPanel("cam3");
    }//GEN-LAST:event_g3LabelMouseClicked
    private void g4LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g4LabelMouseClicked
        setGLabelSelectionToTextAreaAndMainPanel("cam4");
    }//GEN-LAST:event_g4LabelMouseClicked
    private void g5LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g5LabelMouseClicked
        setGLabelSelectionToTextAreaAndMainPanel("cam5");
    }//GEN-LAST:event_g5LabelMouseClicked
    private void setGLabelSelectionToTextAreaAndMainPanel(String cam) {
        List<String> cam1ImagePaths = new ArrayList();
        FileHelperClass fhc = new FileHelperClass();
        for (String path : imagePath) {
            if (fhc.getDirectoryName(path).equals(cam)) {
                cam1ImagePaths.add(path);
            }
        }
        if (!cam1ImagePaths.isEmpty()) {
            imagePahtCopyForCamEvent = cam1ImagePaths;
            imagesJsonPahtCopyForCamEvent = fhc.ChangeFileExtensionToDotJson(cam1ImagePaths);
            BoundingBoxObject bbo = GraphicHelperClass.getInitializedBoundingBoxObject(imagesJsonPahtCopyForCamEvent.get(0));
            setXAndYCoordinates(bbo);
            String recognizedText = getRecognizedText(bbo);
            ImageIcon imageIcon = getScaledImageIconFromImagePath(imagePahtCopyForCamEvent.get(0));

            jTextPane1.setText(recognizedText);
            jLabel9.setHorizontalAlignment(jLabel9.LEADING);
            jLabel9.setIcon(imageIcon);
            repaint(jLabel9.getGraphics());
        }
    }

    public void repaint(Graphics g) {
        super.paint(g);
        Thread t = new Thread(new Runnable() {
            public void run() {
                SwingUtilities.invokeLater(() -> {
                    if (allXCoordinatesOfBoundingBox != null) {
                        int[] tempX = new int[4];
                        int[] tempY = new int[4];
                        int counter = 0;
                        int number = 1;
                        for (int i = 0; i < allXCoordinatesOfBoundingBox.length; i++) {

                            for (int j = 0; j < 4; j++) {
                                tempX[j] = allXCoordinatesOfBoundingBox[counter + j];
                                tempY[j] = allYCoordinatesOfBoundingBox[counter + j];
                            }
                            g.setColor(Color.red);
                            g.drawPolygon(tempX, tempY, 4);
                            g.setColor(Color.GREEN);
                            g.setFont(new Font("Normal", Font.BOLD, 14));
                            g.drawString(number + ") ", (tempX[1] + 5), (tempY[0] + tempY[2]) / 2);
                            counter += 4;
                            number++;
                            if (counter == allXCoordinatesOfBoundingBox.length) {
                                break;
                            }
                        }
                    }
                });
            }
        });
        t.start();
    }

    /**
     * @param args the command line arguments
     */
    private static final String defaultPath = "C:\\Users\\Valerij\\Desktop\\Projekt 2\\OCR";
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Home home = new Home();
                home.setVisible(true);
                home.setTitle("Kaufland - Shelf Management System");
                home.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/logo40.jpg")).getImage());
                currentDirectoryPathField.setText(defaultPath);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel StartLabel;
    private static javax.swing.JTextField currentDirectoryPathField;
    private javax.swing.JPanel footerpanel;
    private static javax.swing.JLabel g1Label;
    private javax.swing.JPanel g1Panel;
    private javax.swing.JLabel g2Label;
    private javax.swing.JPanel g2Panel;
    private javax.swing.JLabel g3Label;
    private javax.swing.JPanel g3Panel;
    private javax.swing.JLabel g4Label;
    private javax.swing.JPanel g4Panel;
    private javax.swing.JLabel g5Label;
    private javax.swing.JPanel g5Panel;
    private javax.swing.JPanel gallaryview3;
    private javax.swing.JPanel galleryViewPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelGalleryImage3;
    private javax.swing.JLabel jLabelLogoImage;
    private javax.swing.JLabel jLabelReportingLabel;
    private javax.swing.JLabel jLabelSettingsImage;
    private javax.swing.JLabel jLabelVirtualImage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lastImage;
    private javax.swing.JPanel logopanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nextImage;
    private javax.swing.JButton openDirectoryButton;
    private javax.swing.JPanel reporting;
    private javax.swing.JPanel reportingPanel;
    private javax.swing.JPanel settings;
    private javax.swing.JPanel settingsPanel;
    private javax.swing.JPanel sidepanel3;
    private javax.swing.JPanel virtualRunaroundPanel;
    private javax.swing.JPanel virtualrunaround;
    // End of variables declaration//GEN-END:variables
}
