/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hhz.graphicaluserinterface;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Valerij
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidepanel3 = new javax.swing.JPanel();
        gallaryview3 = new javax.swing.JPanel();
        jLabelGalleryImage3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        virtualrunaround = new javax.swing.JPanel();
        jLabelVirtualImage = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        reporting = new javax.swing.JPanel();
        jLabelReportingLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        settings = new javax.swing.JPanel();
        jLabelSettingsImage = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        logopanel = new javax.swing.JPanel();
        jLabelLogoImage = new javax.swing.JLabel();
        footerpanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        galleryViewPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        g1Panel = new javax.swing.JPanel();
        g2Panel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        g3Panel = new javax.swing.JPanel();
        g4Panel = new javax.swing.JPanel();
        g5Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        virtualRunaroundPanel = new javax.swing.JPanel();
        reportingPanel = new javax.swing.JPanel();
        settingsPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        sidepanel3.setBackground(new java.awt.Color(204, 35, 42));
        sidepanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gallaryview3.setBackground(new java.awt.Color(160, 35, 42));
        gallaryview3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gallaryviewMouseClicked(evt);
            }
        });

        jLabelGalleryImage3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGalleryImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gallery.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gallery View");

        javax.swing.GroupLayout gallaryview3Layout = new javax.swing.GroupLayout(gallaryview3);
        gallaryview3.setLayout(gallaryview3Layout);
        gallaryview3Layout.setHorizontalGroup(
            gallaryview3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gallaryview3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelGalleryImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        gallaryview3Layout.setVerticalGroup(
            gallaryview3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gallaryview3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(gallaryview3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(jLabelGalleryImage3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidepanel3.add(gallaryview3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 280, -1));

        virtualrunaround.setBackground(new java.awt.Color(204, 35, 42));
        virtualrunaround.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                virtualrunaroundMouseClicked(evt);
            }
        });

        jLabelVirtualImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVirtualImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Virtual Runaround");

        javax.swing.GroupLayout virtualrunaroundLayout = new javax.swing.GroupLayout(virtualrunaround);
        virtualrunaround.setLayout(virtualrunaroundLayout);
        virtualrunaroundLayout.setHorizontalGroup(
            virtualrunaroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(virtualrunaroundLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelVirtualImage, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        virtualrunaroundLayout.setVerticalGroup(
            virtualrunaroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(virtualrunaroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(virtualrunaroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(jLabelVirtualImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidepanel3.add(virtualrunaround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 280, -1));

        reporting.setBackground(new java.awt.Color(204, 35, 42));
        reporting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportingMouseClicked(evt);
            }
        });

        jLabelReportingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReportingLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/analysis.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Reporting");

        javax.swing.GroupLayout reportingLayout = new javax.swing.GroupLayout(reporting);
        reporting.setLayout(reportingLayout);
        reportingLayout.setHorizontalGroup(
            reportingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportingLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelReportingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        reportingLayout.setVerticalGroup(
            reportingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(reportingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(jLabelReportingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidepanel3.add(reporting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 280, -1));

        settings.setBackground(new java.awt.Color(204, 35, 42));
        settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsMouseClicked(evt);
            }
        });

        jLabelSettingsImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSettingsImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/settings.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Settings");

        javax.swing.GroupLayout settingsLayout = new javax.swing.GroupLayout(settings);
        settings.setLayout(settingsLayout);
        settingsLayout.setHorizontalGroup(
            settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelSettingsImage, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        settingsLayout.setVerticalGroup(
            settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel11)
                    .addComponent(jLabelSettingsImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidepanel3.add(settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 280, -1));

        logopanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabelLogoImage.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLogoImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogoImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kauflandLogo.png"))); // NOI18N

        javax.swing.GroupLayout logopanelLayout = new javax.swing.GroupLayout(logopanel);
        logopanel.setLayout(logopanelLayout);
        logopanelLayout.setHorizontalGroup(
            logopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logopanelLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabelLogoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        logopanelLayout.setVerticalGroup(
            logopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logopanelLayout.createSequentialGroup()
                .addComponent(jLabelLogoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sidepanel3.add(logopanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 280, 30));

        footerpanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("© Copyright by HHZ");

        javax.swing.GroupLayout footerpanelLayout = new javax.swing.GroupLayout(footerpanel);
        footerpanel.setLayout(footerpanelLayout);
        footerpanelLayout.setHorizontalGroup(
            footerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerpanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        footerpanelLayout.setVerticalGroup(
            footerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerpanelLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sidepanel3.add(footerpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 280, 30));

        jPanel1.add(sidepanel3, java.awt.BorderLayout.PAGE_START);

        mainPanel.setLayout(new java.awt.CardLayout());

        galleryViewPanel.setBackground(new java.awt.Color(255, 255, 153));
        galleryViewPanel.setLayout(new java.awt.GridLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 710, 470));

        g1Panel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout g1PanelLayout = new javax.swing.GroupLayout(g1Panel);
        g1Panel.setLayout(g1PanelLayout);
        g1PanelLayout.setHorizontalGroup(
            g1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );
        g1PanelLayout.setVerticalGroup(
            g1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.add(g1Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, -1, 131));

        g2Panel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout g2PanelLayout = new javax.swing.GroupLayout(g2Panel);
        g2Panel.setLayout(g2PanelLayout);
        g2PanelLayout.setHorizontalGroup(
            g2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );
        g2PanelLayout.setVerticalGroup(
            g2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.add(g2Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, -1, 131));

        jScrollPane2.setViewportView(jTextPane1);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(815, 41, 243, 649));

        g3Panel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout g3PanelLayout = new javax.swing.GroupLayout(g3Panel);
        g3Panel.setLayout(g3PanelLayout);
        g3PanelLayout.setHorizontalGroup(
            g3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );
        g3PanelLayout.setVerticalGroup(
            g3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.add(g3Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, -1, 131));

        g4Panel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout g4PanelLayout = new javax.swing.GroupLayout(g4Panel);
        g4Panel.setLayout(g4PanelLayout);
        g4PanelLayout.setHorizontalGroup(
            g4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );
        g4PanelLayout.setVerticalGroup(
            g4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
        );

        jPanel3.add(g4Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 560, -1, -1));

        g5Panel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout g5PanelLayout = new javax.swing.GroupLayout(g5Panel);
        g5Panel.setLayout(g5PanelLayout);
        g5PanelLayout.setHorizontalGroup(
            g5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );
        g5PanelLayout.setVerticalGroup(
            g5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
        );

        jPanel3.add(g5Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 560, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 60, 90));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/next.png"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 590, 50, 70));

        galleryViewPanel.add(jPanel3);

        mainPanel.add(galleryViewPanel, "card5");

        virtualRunaroundPanel.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout virtualRunaroundPanelLayout = new javax.swing.GroupLayout(virtualRunaroundPanel);
        virtualRunaroundPanel.setLayout(virtualRunaroundPanelLayout);
        virtualRunaroundPanelLayout.setHorizontalGroup(
            virtualRunaroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1068, Short.MAX_VALUE)
        );
        virtualRunaroundPanelLayout.setVerticalGroup(
            virtualRunaroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        mainPanel.add(virtualRunaroundPanel, "card4");

        reportingPanel.setBackground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout reportingPanelLayout = new javax.swing.GroupLayout(reportingPanel);
        reportingPanel.setLayout(reportingPanelLayout);
        reportingPanelLayout.setHorizontalGroup(
            reportingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1068, Short.MAX_VALUE)
        );
        reportingPanelLayout.setVerticalGroup(
            reportingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        mainPanel.add(reportingPanel, "card3");

        settingsPanel.setBackground(new java.awt.Color(102, 102, 0));

        javax.swing.GroupLayout settingsPanelLayout = new javax.swing.GroupLayout(settingsPanel);
        settingsPanel.setLayout(settingsPanelLayout);
        settingsPanelLayout.setHorizontalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1068, Short.MAX_VALUE)
        );
        settingsPanelLayout.setVerticalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        mainPanel.add(settingsPanel, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void settingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseClicked
        //removing panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        //adding virtualrunaroundPanel
        mainPanel.add(settingsPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_settingsMouseClicked

    private void reportingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportingMouseClicked
        //removing panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        //adding virtualrunaroundPanel
        mainPanel.add(reportingPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_reportingMouseClicked

    private void virtualrunaroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_virtualrunaroundMouseClicked
        //removing panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        //adding virtualrunaroundPanel
        mainPanel.add(virtualRunaroundPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_virtualrunaroundMouseClicked

    private void gallaryviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gallaryviewMouseClicked
       //removing panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        //adding virtualrunaroundPanel
        mainPanel.add(galleryViewPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_gallaryviewMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel footerpanel;
    private javax.swing.JPanel g1Panel;
    private javax.swing.JPanel g2Panel;
    private javax.swing.JPanel g3Panel;
    private javax.swing.JPanel g4Panel;
    private javax.swing.JPanel g5Panel;
    private javax.swing.JPanel gallaryview;
    private javax.swing.JPanel gallaryview1;
    private javax.swing.JPanel gallaryview2;
    private javax.swing.JPanel gallaryview3;
    private javax.swing.JPanel galleryViewPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelGalleryImage;
    private javax.swing.JLabel jLabelGalleryImage1;
    private javax.swing.JLabel jLabelGalleryImage2;
    private javax.swing.JLabel jLabelGalleryImage3;
    private javax.swing.JLabel jLabelLogoImage;
    private javax.swing.JLabel jLabelReportingLabel;
    private javax.swing.JLabel jLabelSettingsImage;
    private javax.swing.JLabel jLabelVirtualImage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelBg;
    private javax.swing.JPanel jPanelBg1;
    private javax.swing.JPanel jPanelBg2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JPanel logopanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel reporting;
    private javax.swing.JPanel reportingPanel;
    private javax.swing.JPanel settings;
    private javax.swing.JPanel settingsPanel;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JPanel sidepanel1;
    private javax.swing.JPanel sidepanel2;
    private javax.swing.JPanel sidepanel3;
    private javax.swing.JPanel virtualRunaroundPanel;
    private javax.swing.JPanel virtualrunaround;
    // End of variables declaration//GEN-END:variables
}
